# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Freakdroid's Personal Web Site
email: Wilfredo1285@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Love, learn, work, study, teach and share that's all.
url: "https://freakdroid.github.io" # the base hostname & protocol for your site
twitter_username: Freak_droid
github_username:  Freakdroid
plugins_dir:  _plugins

name:	Blog de Freakdroid

# Build settings
markdown: kramdown

# Permalinks
permalink:           /:title/
baseurl:             ''
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/images/icon.jpg


#Author info
author:
  name:           	 Wilfredo Pérez
  twitter:           GameOverWill
  facebook:          profile.php?id=100012303975458
  linkedin:          wilfredo-roberto-perez-lopez-3b92185b/

#Server
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001
destination:      	 ./_site

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
#Social media
disqus:              freakdroid-github-io # get it on https://disqus.com/admin/